import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Evidence(props) {
  const { nodes, materials } = useGLTF("/assets/models/evidence.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.End_is_Nigh_Poster_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.End_is_Nigh_Poster_Ripped_1_aiStandardSurface1_0.geometry
          }
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.End_is_Nigh_Poster_Ripped_2_aiStandardSurface1_0.geometry
          }
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.End_is_Nigh_Poster_Ripped_3_aiStandardSurface1_0.geometry
          }
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.End_is_Nigh_Crumpled_1_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.End_is_Nigh_Crumpled_2_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.End_is_Nigh_Crumpled_3_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wrapping_Paper_3_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Napkin_1_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Napkin_1_Crumpled_1_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Napkin_1_Crumpled_2_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Napkin_2_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Napkin_2_Crumpled_1_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Napkin_2_Crumpled_2_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.End_is_Nigh_Poster_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.End_is_Nigh_Poster_Ripped_1_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.End_is_Nigh_Poster_Ripped_2_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.End_is_Nigh_Poster_Ripped_3_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.End_is_Nigh_Crumpled_1_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.End_is_Nigh_Crumpled_2_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.End_is_Nigh_Crumpled_3_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wrapping_Paper_3_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Napkin_1_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Napkin_1_Crumpled_1_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Napkin_1_Crumpled_2_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Napkin_2_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Napkin_2_Crumpled_1_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Napkin_2_Crumpled_2_lambert1_0.geometry}
          material={materials.lambert1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/evidence.glb");

