version: '3'
services:
  frontend:
    build:
      context: ./frontend
    image: webnovel_frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend 
    image: webnovel_backend
    ports:
      - "3700:3700"