apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traffic-http
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webnovel-service
                port:
                  number: 80
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: webnovel-service
                port:
                  number: 3700
