name: Despliegue en GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Construir y subir imágenes al Docker Hub
      run: |
        docker build -t cristiank/webnovel_frontend:latest -f frontend/Dockerfile .
        docker build -t cristiank/webnovel_backend:latest -f backend/Dockerfile .
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push cristiank/webnovel_frontend:latest
        docker push cristiank/webnovel_backend:latest

    - name: Configurar Google Cloud SDK
      run: |
        gcloud auth activate-service-account --key-file="$GITHUB_WORKSPACE/${{ secrets.GCP_SA_KEY }}"
        gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --zone ${{ secrets.GCP_CLUSTER_ZONE }}
        gcloud auth login
      env:
        CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
        CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 1.1.1

    - name: Configurar kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --zone ${{ secrets.GCP_CLUSTER_ZONE }}

    - name: Desplegar en GKE
      run: kubectl apply -f ~/webnovel/deployment.yaml
