name: Despliegue en GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Construir y subir imágenes al Docker Hub
      run: |
        docker build -t cristiank/webnovel_frontend:latest -f frontend/Dockerfile .
        docker build -t cristiank/webnovel_backend:latest -f backend/Dockerfile .
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push cristiank/webnovel_frontend:latest
        docker push cristiank/webnovel_backend:latest

    - name: Configurar Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}'
        token_format: 'access_token'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    # - name: Install gke-gcloud-auth-plugin
    #   run: |
    #     sudo apt-get install -y google-cloud-sdk
    #     sudo apt-get install -y kubectl-credential-gke

    - name: Configurar kubectl
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --zone ${{ secrets.GCP_CLUSTER_ZONE }}

    - name: Desplegar en GKE
      run: kubectl apply -f ~/webnovel/deployment.yaml
