name: Despliegue en GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    # - name: Construir y subir imágenes al Docker Hub
    #   run: |
    #     docker build -t cristiank/webnovel_frontend:latest -f frontend/Dockerfile .
    #     docker build -t cristiank/webnovel_backend:latest -f backend/Dockerfile .
    #     echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    #     docker push cristiank/webnovel_frontend:latest
    #     docker push cristiank/webnovel_backend:latest

    - name: Configurar Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}'
        token_format: 'access_token'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    # - name: Configurar Docker para autenticación con Google Cloud SDK
    #   run: |
    #     echo "${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}" | gcloud auth activate-service-account --key-file=-
    #     gcloud auth configure-docker -q
    - name: Print Google Cloud SDK version
      run: gcloud version


    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Configurar kubectl
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        KUBECONFIG: ${{ runner.workspace }}/kubeconfig.yaml
      run: |
        gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --zone ${{ secrets.GCP_CLUSTER_ZONE }}

    - name: Desplegar en GKE
      run: |
        kubectl rollout restart deployment/webnovel2023
