name: Despliegue en GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    # - name: Construir y subir imágenes al Docker Hub
    #   run: |
    #     docker build -t cristiank/webnovel_frontend:latest -f frontend/Dockerfile .
    #     docker build -t cristiank/webnovel_backend:latest -f backend/Dockerfile .
    #     echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    #     docker push cristiank/webnovel_frontend:latest
    #     docker push cristiank/webnovel_backend:latest

    - name: Configurar Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}'
        token_format: 'access_token'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configurar Docker para autenticación con Google Cloud SDK
      run: |
        echo "${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}" | gcloud auth activate-service-account --key-file=-
        gcloud auth configure-docker -q

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    # - name: Import Google Cloud SDK GPG key
    #   run: |
    #     gpg --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05
        
    # - name: Install gke-gcloud-auth-plugin
    #   env:
    #     USE_GKE_GCLOUD_AUTH_PLUGIN: True
    #   run: |
    #     sudo apt-get update
    #     curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
    #     echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    #     sudo apt-get update && sudo apt-get install google-cloud-cli
      # sudo apt-get install apt-transport-https ca-certificates gnupg curl sudo
      # sudo apt-get install -y apt-transport-https ca-certificates gnupg
      # echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      # sudo apt-get update
      # sudo apt-get install -y google-cloud-sdk kubectl-credential-gke

    - name: Configurar kubectl
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --zone ${{ secrets.GCP_CLUSTER_ZONE }}

    - name: Desplegar en GKE
      run: kubectl rollout restart deployment/webnovel2023
