name: Automate pull request

on:
  pull_request:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: actions/create-pull-request@v3
        with:
          title: New changes
          body: These are the changes that have been made.
          branch: main