name: Automate pull request

on:
  push:
  pull-request:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          title: New changes
          body: These are the changes that have been made.
          branch: main
