name: Automate push

on:
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Push
        run: |
          git push origin main
      - name: Print error
        run: |
          echo "Error: ${{ steps.push.outputs.error }}"
